### ISSUE TITLE
Resampling PCM data, should it be done on the API or on the client?

### ISSUE THREAD

**Issue by mmtmn** [openai/openai-realtime-api-beta#1]
From what I understood, the API only accepts PCM data in 24,000 Hz.

There are two ways to go about this, one of them is to resample the PCM data via the API and the other is via the client.

the API way:
This is a good approach if you need complete control over the quality of the data being fed into your model or if your clients are too diverse to reliably handle resampling on their own.

the Client way:
If you expect many clients with varying capabilities (some of which may be on devices with ample processing power, others not), this can be a way to optimize server-side resources.

if you guys prioritize consistency and control, the resampling should be on the API side. If the intention is to offload work and ensure your API remains lightweight, client-side resampling would make more sense, especially if you have control over the clients and can enforce this behavior.

I'm personally not sure, so, should resampling the PCM data be done on the API or on the Client?

**Comment by khorwood-openai** [comment]
Right now we would encourage client-side resampling.

In terms of long-term plans I'd defer to the Realtime API team @bakks @jordans-openai @landakram
