### ISSUE TITLE
Could not connect to "wss://api.openai.com/v1/realtime"

### ISSUE THREAD

**Issue by Miciurash** [openai/openai-realtime-api-beta#2]
Getting an error when running it locally. 
![image](https://github.com/user-attachments/assets/49db7f04-1f34-459b-803a-7a379b8e75ba)

**Comment by jacob-restart** [comment]
Same

**Comment by partridgeworks** [comment]
Worth inspecting the actual WS response in your browser, you'll see a status code.  I get:

**> Error during WebSocket handshake: Unexpected response code: 403**

i.e. 'unauthorised'.

Anybody know how/where I am supposed to request access, or why this is coming back as Unauthorised?

**Comment by Abdullamhd** [comment]
same

**Comment by kwood** [comment]
We're having the same issue.

I get a 403 on the websocket upgrade request if I use a real API key. 
If I use a random string for the API key I get a successful connection and a different error message as a websocket message.

**Comment by transitive-bullshit** [comment]
See https://github.com/openai/openai-realtime-console/issues/4

OpenAI is reportedly rolling out realtime API access over the next week or two, so if you're seeing this error, you'll need to wait until your account / API key has access.

**Comment by Miciurash** [comment]
seems to be working now
