### ISSUE TITLE
TCP Latency Issues for Real-Time Audio Streaming

### ISSUE THREAD

**Issue by codearranger** [openai/openai-realtime-api-beta#5]
Description: The current implementation of the OpenAI Realtime API relies on TCP (Transmission Control Protocol) for real-time audio streaming. While TCP ensures reliable, ordered delivery of data, this choice introduces latency that makes it less suitable for real-time applications, particularly in audio streaming. This issue affects the quality and responsiveness of the audio experience.

### Steps to Reproduce:

- Implement real-time audio streaming using the OpenAI Realtime API.

- Introduce network conditions with variable packet loss or congestion.

- Monitor audio quality and latency during the stream.

### Observed Behavior:

- Latency is introduced during audio playback.

- Delays are noticeable when packets are lost and retransmitted.

- Audio quality suffers under network congestion due to TCP’s congestion control mechanisms.

- Head-of-line blocking occurs, causing additional delays when waiting for missing packets to be retransmitted.

### Expected Behavior:

- Real-time audio streaming should prioritize low latency over guaranteed data delivery to maintain a smooth and responsive experience. Packet loss should not cause excessive delays in audio playback.

### Technical Details:

- Reliability over Speed: TCP’s reliability introduces latency due to its need for retransmission and ordered delivery.

- Head-of-Line Blocking: Lost packets prevent subsequent packets from being delivered, causing noticeable audio delays.

- **Congestion Control**: TCP's congestion control mechanisms can throttle the stream, reducing throughput and increasing latency.

- **Buffering**: TCP’s buffering mechanisms also contribute to added latency in real-time scenarios.

**Suggested Fix/Improvement**: Consider switching to a UDP-based protocol for real-time audio streaming, such as:

- WebRTC: A protocol built on UDP and optimized for real-time communication.

- RTP (Real-time Transport Protocol): Commonly used in conjunction with UDP for streaming audio and video.

- QUIC: A newer protocol combining the reliability features of TCP with the speed of UDP, making it more suitable for low-latency real-time applications.

These protocols can handle packet loss more gracefully by prioritizing low latency, potentially skipping lost packets rather than waiting for retransmission.

**Comment by khorwood-openai** [comment]
This is definitely on the roadmap! For now vendors like [LiveKit](https://livekit.io/) provide this layer for you.

**Comment by anthmFS** [comment]
I think LiveKit also ends up having the same problem because it ends up translating the resilient protocols into the same less resilient one on the backend, abstracting the problem but not solving it.


We talk about this kind of problem on https://signalwire.ai where we implement a different strategy with dealing with audio latency to keep the complexity inside the server stack where there is no latency.
